spring.application.name=order-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=SHaikh@778866

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

#=====

jwt.secret=12345678901234567890123456789012
jwt.expiration=86400000

# Spring mail configuration

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=shaikh.maroof@gmail.com
#spring.mail.password= PASSWORD@123
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smaroof579@gmail.com
spring.mail.password=zmzu qybo vicr pvkp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true







## Server Port (Optional)
#server.port=8080
#
## MySQL Database Connection
#spring.datasource.url=jdbc:mysql://localhost:3306/SB2
#
#spring.datasource.username=root
#spring.datasource.password= SHaikh@778866
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
### JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
##
### MySQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#
